theme: jekyll-theme-minimal
title: OpenChain Japan Work Group (JWG)
description: [Japanese](), [English]()
logo: https://github.com/NorioKobota/Onboarding-JWG/raw/master/About_Japan-wg/penguine-japan-wg.png
